### ISSUE TITLE
发送oa消息失败,要怎么解决?

### ISSUE THREAD

**Issue by gclsoft** [open-dingtalk/openapi-demo-java#9]
请求数据的json结构中oa参数对应的值中body参数对应的值中file_count参数对应的值不为整数类型的字符串

```
            // 创建oa消息
            MessageBody.OABody oaBody = new MessageBody.OABody();
            oaBody.setMessage_url("http://www.baidu.com");
            Head head = new Head();
            head.setText("head.text");
            head.setBgcolor("FFBBBBBB");
            oaBody.setHead(head);



Exception in thread "main" com.dingtalk.open.client.common.ServiceException: 请求数据的json结构中oa参数对应的值中body参数对应的值中file_count参数对应的值不为整数类型的字符串
	at com.dingtalk.open.client.transport.OpenServiceProxy.invoke(OpenServiceProxy.java:408)
	at com.sun.proxy.$Proxy4.sendToCorpConversation(Unknown Source)
	at com.alibaba.dingtalk.openapi.demo.message.MessageHelper.send(MessageHelper.java:28)
	at com.alibaba.dingtalk.openapi.demo.Demo.main(Demo.java:191)
```

**Comment by tingyugetc520** [comment]
推荐一个钉钉的Java SDK，封装程度比较高，对开发者比较友好，可以看下
https://github.com/tingyugetc520/DtJava
